### ISSUE TITLE
Null tests (tests that do not compile) are stored as collected tests for RAC

### ISSUE THREAD

**Issue by nmaguirre** [zeminlu/stryker#41]
Null tests (tests that do not compile) are stored as collected tests for RAC. It should be checked that a junit test resulting from recovering the inputs of a SAT verdict does compile correctly, to avoid collecting invalid tests.

**Comment by saiema** [comment]
This is resolved. When using RAC and test generation is enabled, JUnit tests are compiled before adding them to the tests collection.
