### ISSUE TITLE
Serious inefficiency in mujava.app.Reloader.loadClassData 

### ISSUE THREAD

**Issue by nmaguirre** [zeminlu/stryker#43]
A preliminary profile of Stryker shows that mujava.app.Reloader.loadClassData takes more than SAT. Improve this routine to make it more efficient.

**Comment by saiema** [comment]
After I get RAC working again we should check if this is still happening

**Comment by saiema** [comment]
I think this problem is solved, can you check again?

**Comment by saiema** [comment]
Review Reloader history. It is a lot more efficient than before and one of the changes was in that method to reduce file reads. So I'll close this issue.
