### ISSUE TITLE
Separate tests of Stryker and Stryker+RAC

### ISSUE THREAD

**Issue by nmaguirre** [zeminlu/stryker#44]
Tests of Stryker are now well structured using parameterized tests. However, tests of Stryker with and without RAC are merged in a single test class. Separate these tests in different testing classes (maintaining the parameterized nature of the tests) so that profiling can be more easily performed.

**Comment by saiema** [comment]
There's parameterized tests for stryker (rac and no rac) but since rac is not yet working correctly this issue remains open.

Will close when rac is working

**Comment by saiema** [comment]
RAC is now working, I'll check if the existing tests are working.

**Comment by saiema** [comment]
Tests are working, some muJava++ configurations are needed because some tests may be failing because of unsupported code by TACO.
